In [3]:
import numpy as np 
print(np.version.version)


1.26.3


In [23]:
l1=[1,2,3,4]
l2=[[1,2],[3,4]]
l3=[[[1,2],[3,4],[8,9]],[[5,6],[7,8],[1,2]]]
l31=[[[1],[3],[8]],[[5],[7],[1]]]
na=np.array(l1)
# nb=np.array(l2)
nc=np.array(l3)
# nd=np.array(l31)
# print(na,type(na),na.ndim)
# print(nb,type(nb),nb.ndim)
#  Q) acces elements of 3d array and print them one by one.
#1st method-
'''
print(nc,type(nc),nc.ndim)
for i in range(2):             #no. of 2d arrays in 1d array
    for j in range(3):         #no. of 1d arrays in 2d array
        for k in range(2):     #no.of elements in 1d array
            print(nc[i][j][k])
'''

#2nd method-
for i in range(nc.shape[0]):             #no. of 2d arrays in 1d array
    for j in range(nc.shape[1]):         #no. of 1d arrays in 2d array
        for k in range(nc.shape[2]):     #no.of elements in 1d array
            print(nc[i][j][k])

[[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [1 2]]] <class 'numpy.ndarray'> 3
1
2
3
4
8
9
5
6
7
8
1
2


In [20]:
# na.shape
# nb.shape
nc.shape
#shape is a tuple kind of data that displays the dimensions of nd list.
#shape mein phle vla print krega kitni row ya kitne nd arrays hai, 2nd hr row mein kitne elements hai ye print krega

(2, 3, 2)

In [24]:
nb[0,1]
nb[0]

array([1, 2])

In [11]:
# 8th day work- 
import numpy as np 
l1=[1,2,3,4]
na=np.array(l1)
na.dtype
np.arange(1,10,2,dtype='f4')

array([1., 3., 5., 7., 9.], dtype=float32)

In [13]:
np.linspace(0,1,5)
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002849FA7C860>
File:            c:\users\91816\appdata\local\programs\python\python312\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
s

In [14]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [18]:
np.ones((2,5),dtype='i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
np.random.rand(2,5)   #rand(shape)any random no. array displayed

array([[0.10393899, 0.72291847, 0.57167866, 0.35879774, 0.03987606],
       [0.95937668, 0.61637048, 0.95856827, 0.9471248 , 0.99144432]])

In [29]:
na = np.arange(1,13)
na=na.reshape((-1,4))  #-1 automatically creates dimensions if u dont wanna calculate them
na.reshape(2,-1,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
b=na[0:2,2:4]   # first is for rows then comma after that is for columns
b=np.array([[10,20],[30,40]])
b

array([[10, 20],
       [30, 40]])

In [32]:
# na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a=na[0:2,3:4].copy()
a[0,0]=10
print(a)
print(na)

[[10]
 [40]]
[[ 1  2 10 10]
 [ 5  6 30 40]
 [ 9 10 11 12]]


In [50]:
np.shares_memory(na,a)

False

In [66]:
b=np.array([[10,20],[30,40]])
b-10,np.add(b,10)

(array([[ 0, 10],
        [20, 30]]),
 array([[20, 30],
        [40, 50]]))

In [56]:
b**2

array([[ 100,  400],
       [ 900, 1600]])

In [57]:
a+b

array([[20, 30],
       [70, 80]])

In [64]:
b[b>7]

array([20, 30, 40])

In [71]:
a=np.arange(1,21)
np.where(a%4==0)

(array([ 3,  7, 11, 15, 19], dtype=int64),)

In [76]:
na=np.arange(1,13).reshape((2,3,2))
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [81]:
np.sum(na,axis=2)  #axis=0-column wise , 1=row wise addition

array([[ 3,  7, 11],
       [15, 19, 23]])