In [3]:
import numpy as np 
print(np.version.version)


1.26.3


In [23]:
l1=[1,2,3,4]
l2=[[1,2],[3,4]]
l3=[[[1,2],[3,4],[8,9]],[[5,6],[7,8],[1,2]]]
l31=[[[1],[3],[8]],[[5],[7],[1]]]
# na=np.array(l1)
# nb=np.array(l2)
nc=np.array(l3)
# nd=np.array(l31)
# print(na,type(na),na.ndim)
# print(nb,type(nb),nb.ndim)
#  Q) acces elements of 3d array and print them one by one.
#1st method-
'''
print(nc,type(nc),nc.ndim)
for i in range(2):             #no. of 2d arrays in 1d array
    for j in range(3):         #no. of 1d arrays in 2d array
        for k in range(2):     #no.of elements in 1d array
            print(nc[i][j][k])
'''

#2nd method-
for i in range(nc.shape[0]):             #no. of 2d arrays in 1d array
    for j in range(nc.shape[1]):         #no. of 1d arrays in 2d array
        for k in range(nc.shape[2]):     #no.of elements in 1d array
            print(nc[i][j][k])

[[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [1 2]]] <class 'numpy.ndarray'> 3
1
2
3
4
8
9
5
6
7
8
1
2


In [20]:
# na.shape
# nb.shape
nc.shape
#shape is a tuple kind of data.
#shape mein phle vla print krega kitni row ya kitne nd arrays hai, 2nd hr row mein kitne elements hai ye print krega

(2, 3, 2)

In [24]:
nb[0,1]
nb[0]

array([1, 2])

TypeError: 'list' object cannot be interpreted as an integer